---

title: Docs
themesDir: themes
#theme: godocs-1
#theme: godocs-2
#theme: godocs-3
theme: godocs-4

publishDir: public

googleAnalytics: "G-75QSQ6BKDP"

disableLanguages: []

outputs:
  home:
    - HTML
    - JSON

markup:
  goldmark:
    renderer:
      unsafe: true

params:

  plugins:

    css:
      - link: plugins/bootstrap/bootstrap.min.css
      - link: plugins/search/auto-complete.css
      - link: plugins/featherlight/featherlight.min.css

    js:
      - link: plugins/jQuery/jquery.min.js
      - link: plugins/bootstrap/bootstrap.min.js
      - link: >-
          https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.2/js/all.min.js
        attributes: crossorigin='anonymous' defer='defer' data-search-pseudo-elements
      - link: plugins/masonry/masonry.min.js
      - link: plugins/featherlight/featherlight.min.js
      - link: plugins/clipboard/clipboard.min.js
      - link: plugins/search/auto-complete.js
      - link: plugins/search/search.js
      - link: plugins/search/lunr.min.js
      - link: plugins/search/fuse.min.js
      - link: plugins/search/mark.js
      - link: plugins/search/search-page.js

  variables:
    primary_color: '#FF0043'
    text_color: '#333'
    text_color_dark: '#222'
    text_color_light: '#999'
    body_color: '#fff'
    border_color: '#E2E2E2'
    black: '#000'
    white: '#fff'
    light: '#FBFBFB'
    primary_font: 'Montserrat:wght@300;400;500;600;700;800'
    primary_font_type: sans-serif
    secondary_font: ''
    secondary_font_type: ''
    icon_font: Font Awesome 5 Free

  author: Salt Labs
  description: Salt Labs documentation.
  contact_form_action: '#'
  feedback_form_action: '#'

  logo:
    main: images/logo.png
    favicon: images/favicon.png
    main_site_link: 'https://docs.saltlabs.tech'
    logo_icon: images/logo-icon.png
    site_logo: images/logo-site.png
    docs_logo: images/logo-docs.png

  preloader:
    enable: false
    preloader: ''

  nav_button:
    - style: outline
      label: changelog
      link: changelog/
    - style: solid
      label: contact
      link: contact/

  social:
    #- title: facebook
    #  icon: fab fa-facebook
    #  link: '#'
    #- title: twitter
    #  icon: fab fa-twitter
    #  link: '#'
    - title: github
      icon: fab fa-github
      link: 'https://github.com/salt-labs'
    #- title: linkedin
    #  icon: fab fa-linkedin
    #  link: '#'

Languages:
  en:
    languageName: En
    languageCode: en-us
    weight: 1
    copyright: >-
      [Salt Labs](https://saltlabs.tech)
    banner:
      title: Documentation
      subtitle: >-
        An unofficial collection of guides tips and tutorials on VMware products.
      image: images/banner.jpg
    feedback:
      title: Did you find this doc useful?
      content: Your feedback helps us improve our docs.
      positive_placeholder: What did you like about this doc?
      negative_placeholder: What can we improve in this doc?
    call_to_action:
      enable: true
      title: Still Didn't Find Your Answer?
      image: images/cta-illustration.jpg
      content: >-
        Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam <br>
        nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam
      button:
        enable: 'true'
        label: Submit a ticket
        link: contact/
    menu:
      footer:
        - name: Changelog
          url: changelog/
          weight: 1
        - name: Contact
          url: contact/
          weight: 2
        - name: Github
          url: 'https://github.com/salt-labs/'
          weight: 3
