---

main:

  - name: Home
    url: ''
    weight: 1

  - name: Salt Labs
    url: https://saltlabs.tech
    weight: 2

  - name: Docs
    url: https://docs.saltlabs.tech
    weight: 3

  - name: Presentations
    url: https://presentations.saltlabs.tech
    weight: 4

footer:

  - name: Changelog
    url: changelog/
    weight: 1

  - name: Contact
    url: contact/
    weight: 2

  - name: Github
    url: 'https://github.com/salt-labs/'
    weight: 3
