---
baseURL: http://localhost:1313

# Show pages not yet published
buildDrafts: true

# Auto-load the page that changed
navigateToChanged: true

# Disable Fast Render mode
disableFastRender: true

# Enable watching for changes and auto-rebuild
watch: true
